In [6]:
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
# Arrays

In [3]:
l1=[3,6,8,3,2]
l1

[3, 6, 8, 3, 2]

In [4]:
type(l1)

list

In [5]:
arr1=np.array([3,6,8,3,2])
arr1

array([3, 6, 8, 3, 2])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
len(arr1)

5

In [12]:
arr1[-1]

2

In [13]:
arr1[0:3]

array([3, 6, 8])

In [14]:
arr1

array([3, 6, 8, 3, 2])

In [15]:
print(arr1)

[3 6 8 3 2]


In [16]:
# Numpy: Numerical Python

In [18]:
arr1

array([3, 6, 8, 3, 2])

In [32]:
arr1.shape

(5,)

In [29]:
arr1.ndim

1

In [22]:
arr1.size

5

In [25]:
arr1.dtype

dtype('int32')

In [19]:
arr2=np.array([[1,3,6],[5,3,7]])
arr2

array([[1, 3, 6],
       [5, 3, 7]])

In [33]:
arr2.shape

(2, 3)

In [30]:
arr2.ndim

2

In [28]:
arr2.dtype

dtype('int32')

In [23]:
arr2.size

6

In [20]:
arr3=np.array([[[1,2,5],[3,4,8]],[[4,5,7],[5,6,9]]])
arr3

array([[[1, 2, 5],
        [3, 4, 8]],

       [[4, 5, 7],
        [5, 6, 9]]])

In [37]:
arr3.shape

(2, 2, 3)

In [31]:
arr3.ndim

3

In [24]:
arr3.size

12

In [38]:
# Numpy attributes
# count         : arr.size      : number of elements in an array
# shape         : arr.shape     : number of elements in each dimension/axis
# dimension     : arr.ndim      : number of dimensions/axis in the array
# datatype      : arr.dtype     : datatype of elements of the array

# when values within shape are multiplied, it should be equal to size of the array
# the number of values in shape attribute is equal to number of dimensions


In [27]:
# Datatypes
# int           int8,int16,int32,int64,uint8,uint16,uint32, etc.
# float         float16,float32, etc.
# str           U32,U16,object,etc.

In [ ]:
# range from -2^(n-1) to (2^(n-1))-1
# int8:  -2^7 to (2^7)-1 : -128 to 127
# int16: -2^15 to (2^15)-1: -32768 to 32767
# uint8: 0 to (2^8)-1: 0 to 255